api/urls.py
from django.conf.urls import url
from . import views

app_name = "api"

urlpatterns = [
    url(r'^PlayerData/$', views.getPlayers, name="players"),
    url(r'^TeamCreatedData/$', views.getTeamCreated, name="team_created"),
    url(r'^TeamPlayersData/$', views.getTeamPlayers, name="team_players"),
    url(r'^SeriesListData/$', views.getSeriesList, name="series_list"),
    url(r'^SeriesSquadsData/$', views.getSeriesSquads, name="series_squads"),
    url(r'^MatchData/$', views.getMatches, name="matches"),
    url(r'^LeaderBoard/$', views.UserPointsByMatch, name="userPoints"),
    url(r'^FantasyStats/$', views.playerPointByMatch, name="fantasystats"),
    url(r'^playerHistory/$', views.getPointsOfCertainPlayer, name="pointOfAPlayer"),
    url(r'^leagues/$', views.saveLeague, name="saveLeague"),
    url(r'^joinLeague/$', views.joinLeague, name="joinLeague"),
    url(r'^leagueInfo/$', views.LeagueInfo, name="leagueInfo"),
    url(r'^userLeagues/$', views.userLeagues, name="userLeagues"),
    url(r'^userSignupOld/$', views.getUser, name="usersignupold"),
    url(r'^removePlayers/$', views.removePlayers, name="usersignupold"),
]

core/urls.py
from django.conf.urls import url
from . import views

app_name="core"

urlpatterns = [
    url(r'^login/loggedIN/$', views.coredex, name="index")
]

dream11/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dream11/', include('user_registration.urls')),
    url(r'^dream11/core/', include('core.urls')),
    url(r'^dream11/api/', include('api.urls')),
    url(r'^rest-auth/', include('rest_auth.urls')),
    url(r'^rest-auth/registration/', include('rest_auth.registration.urls'))
]

user_registration/urls.py
from . import views
from django.conf.urls import url, include

app_name = "user_registration"


urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^register/$', views.register, name="register"),
    url(r'^register/login/$', views.registration, name="registration"),
    url(r'^login/$', views.login, name="login"),
    url(r'^Admin/$', views.Admin, name='admin'),
    url(r'^update_points/$', views.update_user_points, name='update_points'),
    url(r'^Admin/csv/$', views.upload_csv, name='upload_csv'),
    url(r'^login/loggedIN/CRT/$', include('create_team.urls')),
]

user_registration/models.py
from django.db import models
from django.core.validators import MaxLengthValidator

# class Users(models.Model):
#     name = models.CharField(default="", max_length=250)
#     email = models.CharField(max_length=250)
#     password = models.CharField(max_length=250)
#     contests = models.TextField(default="[]")

#     def __str__(self):
#         return self.email+' - '+self.password

class Players(models.Model):
    name = models.CharField(default="", max_length=250)
    country = models.CharField(max_length=250)
    image = models.CharField(max_length=500)
    role = models.CharField(max_length=30)
    credit = models.FloatField(default=None)

    def __str__(self):
        return self.name + ' - ' + self.role + ' - ' + self.country

class Users(models.Model):
    name = models.CharField(default="noName", max_length=250)
    email = models.EmailField(max_length=250)
    password = models.CharField(max_length=250,validators=[MaxLengthValidator(limit_value=8, message="password must be at least 8 characters long")])
    contests = models.CharField(max_length=100,default='')
    def __str__(self):
        return self.name+' - '+self.email

user_registration/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .crawler import crawling,insert_player_info_db
from .data_insert  import insert_crawled_data, insert_credit, insert_non_ranked_credit, insert_all_players, user_team_insert, insert_match_scorecard, insert_user_points
from django.shortcuts import render
from .models import Users,Players
import csv
from django.core.signing import Signer



def index(request):
    return render(request, 'home/index.html',{})


def registration(request):
    name = request.POST['namei']
    email = request.POST['email']
    password = request.POST['password']
    signer = Signer()
    Hashed_pass = signer.sign(password).split(':',1)
    newuser = Users(name=name, email=email, password=Hashed_pass[1])
    newuser.save()
    return render(request, 'login.html', {})


def login(request):
    return render(request, 'login.html', {})


def loggedin(request):
    email = request.POST['email']
    password = request.POST['password']
    signer = Signer()
    original = signer.sign(password).split(':',1)
    user = get_object_or_404(Users,email=email,password=original[1])
    playerlist = Players.objects.all()
    return render(request, 'playerList.html',{'playerlist' : playerlist})

def upload_csv(request):
    if request.POST:
        file = request.FILES['csv_file']
        decoded_file = file.read().decode('utf-8').splitlines()
        reader = csv.DictReader(decoded_file)
        for row in reader:
            if len(row) == 4:
                insert_player_info_db(row)
    return render(request, 'home/admin.html', {})


def player_search(request):
    search_keyword = request.GET['keyword']
    playerlist = Players.objects.all()
    search_result = []
    for player in playerlist:
        name = player.name.lower()
        search_keyword = search_keyword.lower()
        if search_keyword in name:
            print(player.name)
            search_result.append(player)
    return render(request, 'playerList.html',{'playerlist' : search_result})

def profileView(request,name):
    player_profile = Players.objects.get(name=name)
    return render(request,'profile.html',{'profile' : player_profile})



def register(request):
    return render(request, 'registration.html' )


def Admin(request):
    # crawling()
    # Players.objects.all().delete()
    # insert_crawled_data()
    # insert_credit()
    # insert_non_ranked_credit()
    # insert_all_players()
    # user_team_insert()
    insert_match_scorecard(908, 1, 'ICC Cricket World Cup 2019')
    return render(request, 'home/admin.html',{})

def update_user_points(request):
    insert_match_scorecard(1, 1, 'ICC Cricket World Cup 2019')
    return render(request, 'home/admin.html')

# Create your views here.

user_registration/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}
    {% endblock %}

	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-theme.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<!--===============================================================================================-->

</head>
<body>

	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-form-title" style="background-image: url({% static 'images/bg-01.jpg' %});">
					<span class="login100-form-title-1">
                        {% block sign_up_or_in %}
                        {% endblock %}
					</span>
				</div>

				<form class="login100-form validate-form" id="Registration_form" method="post" {% block action %} {% endblock %}>
                    {% csrf_token %}
                    {% block username %}
                    {% endblock %}


					<div class="wrap-input100 validate-input m-b-26" data-validate="Email is required">
						<span class="label-input100">Email</span>
						<input class="input100" id="form_email" type="text" name="email" placeholder="Enter email">
                        <span class="focus-input100"></span>
                        <span class="error_form" id="email_error_message"> </span>

					</div>

                <!--    <div class="form-group has-feedback">
                      <label for="password"  class="col-md-4 control-label">
                         Password
                         </label>
                        <div class="col-md-6  inputGroupContainer">
                            <div class="input-group"> <span class="input-group-addon"><i class="glyphicon glyphicon-home"></i></span>
                                <input class="form-control" id="userPw" type="password" placeholder="password"
                                    name="password" data-minLength="5"
                                    data-error="some error"
                                    required/>
                                    <span class="glyphicon form-control-feedback"></span>
                                    <span class="help-block with-errors"></span>
                            </div>
                        </div>
                    </div> -->

					<div class="wrap-input100 validate-input m-b-18" data-validate = "Password is required">
						<span class="label-input100">Password</span>
						<input class="input100" id="form_password" type="password" name="password" placeholder="Enter password">
                        <span class="focus-input100"></span>
                        <span class="error_form" id="password_error_message"></span>

					</div>

					<div class="flex-sb-m w-full p-b-30">
						<div class="contact100-form-checkbox">
							<input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
							<label class="label-checkbox100" for="ckb1">
								Remember me
							</label>
						</div>

						<div>
							<a href="#" class="txt1">
								Forgot Password?
							</a>
						</div>
					</div>

					<div class="container-login100-form-btn" >
						<!--<button class="login100-form-btn">Login</button> -->
                        {% block login_or_register %}
                        {% endblock %}

					</div>
				</form>
			</div>
		</div>
	</div>

<!--===============================================================================================-->
	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'js/main.js'%}"></script>
<!--===============================================================================================-->
    <script src="{% static 'js/validation.js' %}"></script>

</body>
</html>

user_registration/templates/login.html
{% extends 'base.html' %}

{% block title %}
    <title>Sign in</title>
{% endblock %}
{% block sign_up_or_in %}
    Sign In
{% endblock %}

{% block action %}
    action="{% url 'core:index' %}"
{% endblock %}
{% block username %}
{% endblock %}

{% block login_or_register %}
    <input class="button" type="submit" value="Login" name="Login" href="#">
{% endblock %}

user_registration/templates/playerList.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>Player list</title>


    <link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.css'>

    <link rel="stylesheet" href="{% static 'css/playerListCard.css' %} ">

    <link href="{% static 'css/search.css' %}" rel="stylesheet" />

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

    <!--
    <link rel="apple-touch-icon" href="{% static '_team/images/apple-touch-icon.png' %}">
    <link rel="shortcut icon" type="image/ico" href="{% static '_team/images/favicon.ico' %}" />
    <!-- Plugin-CSS -->
    <!--
    <link rel="stylesheet" href="{% static '_team/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static '_team/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static '_team/css/linearicons.css' %}">
    <link rel="stylesheet" href="{% static '_team/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static '_team/css/animate.css' %}">
    <!-- Main-Stylesheets -->
    <!--
    <link rel="stylesheet" href="{% static '_team/css/normalize.css' %}">
    <link rel="stylesheet" href="{% static '_team/style.css' %}">
    <link rel="stylesheet" href="{% static '_team/css/responsive.css' %}">
    <script src="{% static '_team/js/vendor/modernizr-2.8.3.min.js' %}"></script> -->


</head>

<body>

        <div class="s130">
        <form action="{% url 'user_registration:search' %}">
            <div class="inner-form">
                <div class="input-field first-wrap">
                    <div class="svg-wrapper">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                            <path d="M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z"></path>
                        </svg>
                    </div>
                    <input id="search" name="keyword" type="text" placeholder="Which player are you looking for?" />
                </div>
                <div class="input-field second-wrap">
                    <button class="btn-search" type="submit">SEARCH</button>
                </div>
            </div>
            <!-- <span class="info">ex. Game, Music, Video, Photography</span> -->
      </form>
    </div>




   <!--  <div class="preloader">
        <span><i class="lnr lnr-sun"></i></span>
    </div> -->
    <!-- MainMenu-Area -->
   <!-- <nav class="mainmenu-area" data-spy="affix" data-offset-top="200">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#primary_menu">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!--<a class="navbar-brand" href="#"><img src="images/logo.png" alt="Logo"></a> -->
          <!--  </div> -->
        <div class="container-fluid">
            <div class="btn-group btn-group-justified">

                    <a href="#" class="btn btn-primary">Wicketkeeper</a>
                <a href="#" class="btn btn-primary">Batsman</a>
                  <a href="#" class="btn btn-primary">Bowler</a>
                  <a href="#" class="btn btn-primary">All Rounder</a>


                </div>
        </div>

    <!--    </div>
    </nav> -->
    <!-- MainMenu-Area-End -->
    <!-- Home-Area -->



    <!-- <div class="search_bar">
        <form action="{% url 'user_registration:search' %}">
                <input type="text" class="textbox" name="keyword" placeholder="Search">
                <input title="Search" type="submit" class="button">
        </form>
    </div> -->
    <div class="container-fluid">
        {% for i in playerlist %}
        <div class="profile">
        <div class="photo"><img src="{{ i.image }}" /></div>
        <div class="content">
            <div class="text">
                <a href="{% url 'user_registration:profile' name=i.name %}">{{ i.name }}</a>
                <h6>{{ i.country }}</h6>
            </div>
            <div class="btn">
                <span></span>
            </div>
        </div>
        <!--<div class="box"><i class="fa fa-codepen"></i><i class="fa fa-facebook"></i><i class="fa fa-github"></i><i class="fa fa-tumblr"></i><i class="fa fa-twitter"></i></div>-->
    </div>
    {% endfor %}
    </div>



    <script src="{% static 'js/playerListCard.js' %}"></script>

    <script src="{% static 'js/search/extention/choices.js' %}"></script>
     <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
     <script src="{% static 'profile/js/bootstrap.min.js' %}"></script>
    <!--Vendor-JS-->
    <!--
    <script src="{% static '_team/js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static '_team/js/vendor/jquery-ui.js' %}"></script>
    <script src="{% static '_team/js/vendor/bootstrap.min.js' %}"></script>
    <!--Plugin-JS-->
    <!--
    <script src="{% static '_team/js/owl.carousel.min.js' %}"></script>
    <script src="{% static '_team/js/contact-form.js' %}"></script>
    <script src="{% static '_team/js/ajaxchimp.js' %}"></script>
    <script src="{% static '_team/js/scrollUp.min.js' %}"></script>
    <script src="j{% static '_team/js/magnific-popup.min.js' %}"></script>
    <script src="{% static '_team/js/wow.min.js' %}"></script>
    <!--Main-active-JS-->
    <!--
    <script src="{% static '_team/js/main.js' %}"></script> -->
</body>

</html>

user_registration/templates/profile.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
<link href="{% static 'profile/css/bootstrap.min.css' %}" rel="stylesheet" id="bootstrap-css">
<link href="{% static 'profile/css/profile.css' %}" rel="stylesheet" id="bootstrap-css">
<script src="{% static 'profile/js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{% static 'table/images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'table/vendor/bootstrap/css/bootstrap.min.css' %} ">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'table/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'table/vendor/animate/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'table/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'table/vendor/perfect-scrollbar/perfect-scrollbar.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'table/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'table/css/main.css' %}">
<!--===============================================================================================-->
<!------ Include the above in your HEAD tag ---------->

<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    </head>
<body>
<div>
<div >
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-12 col-sm-4">

            <div class="card hovercard">
                <div class="cardheader" style="background: url('{% static 'images/profile4.jpg' %}')">

                </div>
                <div class="avatar">
                    <img alt="" src="{{ profile.image }}">
                </div>
                <div class="info">
                    <div class="title">
                        {{ profile.name }}
                    </div>
                    <div class="desc">{{ profile.role }}</div>
                    <div class="desc">{{ profile.country }}</div>

                </div>

            </div>

        </div>

	</div>
    </div>
</div>

<div class="container">
  <div class="table-responsive">
  <div class="table100 ver2 m-b-110">
					<table data-vertable="ver2">
						<thead>
							<tr class="row100 head">
								<th class="column100 column1" data-column="column1">Week</th>
								<th class="column100 column2" data-column="column2">Points</th>

							</tr>
						</thead>
						<tbody>
							<tr class="row100">
								<td class="column100 column1" data-column="column1">Lawrence Scott</td>
								<td class="column100 column2" data-column="column2">8:00 AM</td>

							</tr>

							<tr class="row100">
								<td class="column100 column1" data-column="column1">Jane Medina</td>
								<td class="column100 column2" data-column="column2">--</td>
							</tr>

							<tr class="row100">
								<td class="column100 column1" data-column="column1">Billy Mitchell</td>
								<td class="column100 column2" data-column="column2">9:00 AM</td>
							</tr>

							<tr class="row100">
								<td class="column100 column1" data-column="column1">Beverly Reid</td>
								<td class="column100 column2" data-column="column2">--</td>
							</tr>

							<tr class="row100">
								<td class="column100 column1" data-column="column1">Tiffany Wade</td>
								<td class="column100 column2" data-column="column2">8:00 AM</td>

							</tr>

							<tr class="row100">
								<td class="column100 column1" data-column="column1">Sean Adams</td>
								<td class="column100 column2" data-column="column2">--</td>

							</tr>

							<tr class="row100">
								<td class="column100 column1" data-column="column1">Rachel Simpson</td>
								<td class="column100 column2" data-column="column2">9:00 AM</td>

							</tr>

							<tr class="row100">
								<td class="column100 column1" data-column="column1">Mark Salazar</td>
								<td class="column100 column2" data-column="column2">8:00 AM</td>
							
							</tr>
						</tbody>
					</table>
				</div>
  </div>
</div>

<!--===============================================================================================-->
	<script src="{% static 'table/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'table/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'table/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'table/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'table/js/main.js' %}"></script>
</body>
</html>

user_registration/templates/registration.html
{% extends 'base.html' %}

{% block title %}
    <title>Sign up</title>
{% endblock %}
{% block sign_up_or_in %}
    Sign Up
{% endblock %}

{% block action %}
    action="{% url 'user_registration:registration' %}"
{% endblock %}

{% block username %}
    <div class="wrap-input100 validate-input m-b-18">
        <span class="label-input100">Username</span>
        <input class="input100" type="text" name="namei" placeholder="Enter username">
        <span class="focus-input100"></span>
    </div>
{% endblock %}

{% block login_or_register %}
    <input class="button" type="submit" value="Register" name="Register" href="#">
{% endblock %}

user_registration/templates/ss.html
<h1>New User Registration completed</h1>